### ISSUE TITLE
Contact Page needs a file attachment

### ISSUE THREAD

**Issue by jakehockey10** [jakehockey10/clothes_casts_and_care#11]
The message coming from the contact page need to be able to handle file attachments.

We need to know what type of files we are going to allow and what type of files we are **not** going to allow

**Comment by jakehockey10** [comment]
We will be going with just PDFs for now until we decide what else we want to support.

**Comment by jakehockey10** [comment]
Lindsey, can you remind me why we want to have file attachments on the contact form?  If we have a patterns page that lets you upload pattern PDFs, is there anything else we'd want them to be able to upload?  If so, I think we can skip having the contact form have a file attachment field.  What do you think?

**Comment by clothescastscare** [comment]
I didn't think we needed file attachments? If they want to send in a pattern, they can just email me directly and then send it in a later email. I don't think we should let people upload things before they go through me first, so it would probably be easier to not have file attachments. If I want to put it up on the website, then I will actually be the one to upload it.

**Comment by jakehockey10** [comment]
Sounds good to me!  I'm closing the issue and calling this done :)
