### ISSUE TITLE
Need to be able to post blogs

### ISSUE THREAD

**Issue by jakehockey10** [jakehockey10/clothes_casts_and_care#12]
A WYSIWYG editor would be good.
No comments (for now?)

**Comment by jakehockey10** [comment]
Could the blogs just appear on the home page below the carousel?

**Comment by clothescastscare** [comment]
That's what I was thinking. There will probably only be like 3-4 (I think), and they should be pretty short so the whole post can probably go below the carousel without it looking too cluttered.

**Comment by jakehockey10** [comment]
Lindsey,

You are able to create blog posts now.  Will you please let me know if you run into any issues or bugs by adding them as issues here on Github?  I tested it fairly well, but it is late.  Also let me know if you want to change the style of anything :)
