### ISSUE TITLE
Need to be able to upload patterns

### ISSUE THREAD

**Issue by jakehockey10** [jakehockey10/clothes_casts_and_care#13]
Admins need to be able to upload patterns.

What type of pattern files?  PDF for sure.  But anything else?

**Comment by clothescastscare** [comment]
I think we are planning to make them in PDF form. The plan was to write it all out on a piece of paper and then scan them in, so I'm pretty sure that would make it into a PDF. I think those patterns are the only thing on that page, so probs no other type of file.
