### ISSUE TITLE
Remove footer

### ISSUE THREAD

**Issue by jakehockey10** [jakehockey10/clothes_casts_and_care#16]
The footer needs real content.

**Comment by jakehockey10** [comment]
Lindsey,

What would you like to have go in the footer?

**Comment by clothescastscare** [comment]
What usually goes on a footer? I can't think of anything that really needs to go there at the moment.

**Comment by jakehockey10** [comment]
we could remove it too, if you want?

**Comment by clothescastscare** [comment]
Yeah that would probably be best.
