### ISSUE TITLE
Add to About Me Page

### ISSUE THREAD

**Issue by clothescastscare** [jakehockey10/clothes_casts_and_care#18]
Ok for some reason I'm not finding the admin login on the website? I thought it was on the little bar thing at the bottom of the page, but I could be wrong. On the About Me page, there's a typo in the little bio; it says "Tod do" instead of "to do". I would also like to add Kay Shaw to the list of people. I also have this picture to put on the page. Maybe we should get together with Judy on the 26th and you could teach me how to edit the website and we could get that pattern uploaded? 
![lindsey 24](https://cloud.githubusercontent.com/assets/13721686/9837244/20c197b8-59f6-11e5-964d-5b27bed5fc76.jpg)

**Comment by jakehockey10** [comment]
Hey loo bug.  Only way to login as an admin is to go to `http://www.spicacastcare.com/admins/sign_in`.  This way, you have to know that an admin portal even exists before being able to try to sign in.  I'll make these changes real quick :)

**Comment by jakehockey10** [comment]
Do you have the pattern ready to go already?  Can you send it to me, if so?

**Comment by clothescastscare** [comment]
I think Judy has been working on it, but it's not completely done. I need to get together with her for a bit and get it done.
