### ISSUE TITLE
Domain Name

### ISSUE THREAD

**Issue by jakehockey10** [jakehockey10/clothes_casts_and_care#8]
Url Name Ideas:
I want the url to be general enough so that people who are looking at spica stuff could come across my website easily. I was thinking something like spicacare or spicacastcare

**Comment by clothescastscare** [comment]
Hey so I just purchased the domain name spicacastcare.com from namecheap for 1 year. What should I do now, so we can get it hooked up with the website?

**Comment by jakehockey10** [comment]
I added the domain to the heroku app.  You can either go to namecheap again and point the DNS for this domain towards still-hollows-5568.herokuapp.com or you can give me your login information and I can do that for you :)

**Comment by clothescastscare** [comment]
I'm pretty sure my login is clothescastscare (@gmail) and Troop1982 as the password

**Comment by jakehockey10** [comment]
Guess what's working at the domain name you bought???
```
                             __
                            |  |
                           _|  |_
                           \    /
                            \  /
                             \/
```
![selection_007](https://cloud.githubusercontent.com/assets/1821383/9623633/cb81a340-5100-11e5-9c5f-b491a177e213.png)

**Comment by jakehockey10** [comment]
Also, think about a favicon you'd want to use (the icon that appears at the left of the browser tab and at the beginning of the url bar (see picture above).

**Comment by clothescastscare** [comment]
Yay!!!!!!!!!

**Comment by clothescastscare** [comment]
Are there any copyright rules about that? If not we could probably just use the gs logo.

**Comment by jakehockey10** [comment]
I'm a dumb dumb.  What's the gs logo?

**Comment by clothescastscare** [comment]
Girl Scout logo

**Comment by jakehockey10** [comment]
oh.  I guess we can try that and then see if they say anything...  We may just have to mention, more so, your affiliation with Girl Scouts.  Could you find the logo image for me?

**Comment by clothescastscare** [comment]
I mention it in my bio so hopefully that's good enough
